### ISSUE TITLE
Graphic issue: Checkbox in Avatars and controls list

### ISSUE THREAD

**Issue by gioboa** [CreativeIT/material-angular-dashboard#10]
#### Steps to reproduce the behavior

Load demo page and go to Menu -> Components -> Avatars and controls list

![screenshot 2018-12-07 at 10 30 12](https://user-images.githubusercontent.com/35845425/49639509-7a67b000-fa0b-11e8-8e5f-230e721defdb.png)

#### Relevant code

The resolution is 1166px X 801px.
I notice that only if the width has even numbers the graphic issue appear. (1166px, 1218px, 1264px ...)

#### Environment description

macOS Mojave v. 10.14.1 - Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by randrianov** [comment]
@gioboa thank you. I saw vertical line on the checkbox, but haven't reproduce in my env. Will check on macOS later.

**Comment by franckevva** [comment]
It's problem from material.io 
The same in [issue#9](https://github.com/CreativeIT/material-angular-dashboard/issues/9#issuecomment-462662396)
