### ISSUE TITLE
Compilation failure: Cannot find module 'ng-getmdl-select'.

### ISSUE THREAD

**Issue by lkavicky** [CreativeIT/material-angular-dashboard#16]
#### Expected behavior
After `git clone`, `yarn install`, running `ng serve` should compile successfully and serve the dashboard.

#### Actual behavior
`ng serve` returns an error and fails to compile the project:

```
ERROR` in src/app/pages/forms/forms.module.ts(4,38): error TS2307: Cannot find module 'ng-getmdl-select'.
src/app/pages/ui/ui.module.ts(3,38): error TS2307: Cannot find module 'ng-getmdl-select'.

i ｢wdm｣: Failed to compile.
```

**Comment by bala-techguy** [comment]
I'm also getting the same error message as soon as I clone and try to do ng serve.

**Comment by franckevva** [comment]
Hi, guys @lkavicky @bala41288 
Now you can try again, it should be work correctly.
Thanks for your attention
