### ISSUE TITLE
Build this project by the configuration to the production target always be wrong

### ISSUE THREAD

**Issue by RussellCao824** [CreativeIT/material-angular-dashboard#27]
### **Issue type**

- [x] bug
- [ ] feature request
- [ ] question about the decisions made in the repository

### **Issue description**
When i built this project by command  `ng build`  for the test environment,the result is normal and correct.But when i take the command  `ng build --prod` for the production environment,the result always be wrong,The error Info is:

**ERROR in : Can't bind to 'htmlFor' since it isn't a known property of 'ng-component'.**
**1. If 'htmlFor' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.**
**2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("[ERROR ->]<ng-component></ng-component>")** 

I have downloaded the latest code and installed the dependencies ,i don't have any changement of the code,but i got the same error.

**Comment by NilsNaegele** [comment]
Anybody know how to solve this problem? It seems to be linked to the Theme Folder Content.

**Comment by Petterf91** [comment]
Did you find a solution? I'm having the same problem.

**Comment by PauloDerney** [comment]
I had the same problem and got a palliative solution.
In the file toggle.component.ts replace this line:
@HostBinding ('for') @Input () innerID = `base-toggle - $ {ToggleComponent.idCounter + = 1}`;
for this:
@Input () innerID = `base-toggle - $ {ToggleComponent.idCounter + = 1}`;
In this case, the error that occurs is due to this "for".
Probably the build prod points to some more errors due to private properties that should be public, just adjust as indicated in the errors.

**Comment by cheung-chifung** [comment]
I disabled `buildOptimizer` and `aot` in `angular.json`, then it worked.
It's just a workaround, still waiting for a final solution.

**Comment by maxwellCatCoder** [comment]
Good night. Production mode uses the AoT compiler with a build optimizer by default.
For quick solution go in angular.json file, find "configation" -> "production" and switch "aot" and "buildoptimizer" to false.
![image](https://user-images.githubusercontent.com/60538056/89350878-806ad400-d6b9-11ea-864d-5e96dd4e33a5.png)
We are working on the optimization of our dashboard for AoT compiler.
Please stay tuned for a nice solution.
Best regards, CreativeIT.

**Comment by maxwellCatCoder** [comment]
Good evening! I am happy to announce that with commit #8ac2088 we have finished switching to aot compiler. It means that this issue is fixed too.

Happy coding with our products:)
Best regards, CreativeIT.
