### ISSUE TITLE
Profile Info cuts dropdown

### ISSUE THREAD

**Issue by maslaw** [CreativeIT/material-angular-dashboard#7]
#### Expected behavior
Dropdown in Profile Info must be full shown

#### Actual behavior
Profile Info on page 'UI > Forms' have strange overflow for dropdown
https://prnt.sc/lrjiak

#### Steps to reproduce the behavior
Go to page 'UI > Forms'.
In Profile Info block click on Dropdown.

#### Environment description
http://material-angular-dashboard.creativeit.io/

**Comment by randrianov** [comment]
@maslaw thank you for reporting!
