### ISSUE TITLE
New items in an empty TODO list

### ISSUE THREAD

**Issue by amaslakov** [CreativeIT/material-angular-dashboard#8]
#### Expected behavior
Should look the same as when the page loads

#### Actual behavior
I see native checkboxes, layout is broken, placeholder stays when I type in something
![image](https://user-images.githubusercontent.com/10218892/49633374-2f00d200-fa0a-11e8-9f47-8f88ca2764b8.png)

#### Steps to reproduce the behavior
Load demo page, delete all TODO items, start adding new ones

#### Environment description
Ubuntu 18.04, Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by raygervais** [comment]
Able to recreate in Windows 10, Firefox 63.0.3.

Interested in fixing this! 

![image](https://user-images.githubusercontent.com/14265337/49660627-121dcc00-fa15-11e8-96c3-b4edc6c16c2b.png)

**Comment by randrianov** [comment]
@amaslakov thank you for reporting!
@raygervais are you interested in creating pull-request own pull-request?:)

**Comment by raygervais** [comment]
@randrianov , I would be happy to! Will post screens here of tests and results, may also ask for some consulting on best practice in the case that I am not following!

**Comment by raygervais** [comment]
So, I found by adding the following css override, we solve the issue in `todo-list.component.css`: 
```
    .mdl-checkbox__label {
      display: inline-block;
      padding-left: 8px;
    }
```

`8px` may be strong, but I belive some padding to the left is needed based on material spec. Open to discussion of course. Thoughts @randrianov ?

Which makes it appear as the following:
![image](https://user-images.githubusercontent.com/14265337/49693102-1262b800-fb38-11e8-9fff-b84a94cb2d53.png)

**Comment by raygervais** [comment]
@randrianov, if this is appropriate I'll open up a pull request. Just wanting to confirm beforehand 👍

**Comment by franckevva** [comment]
Thank you for participating, we fixed it.
