### ISSUE TITLE
Graphic issue: Project checkbox list - first checkbox

### ISSUE THREAD

**Issue by gioboa** [CreativeIT/material-angular-dashboard#9]
#### Expected behavior

First checkbox should look like others.

#### Actual behavior

First checkbox has graphic issue.

#### Steps to reproduce the behavior

Load demo page and select the first checkbox

![screenshot 2018-12-07 at 10 03 48](https://user-images.githubusercontent.com/35845425/49639067-4b9d0a00-fa0a-11e8-8365-f7415ad3471f.png)

#### Environment description

macOS Mojave v. 10.14.1 - Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by randrianov** [comment]
@gioboa sorry, don't get you what's wrong on the screenshot with the first checkbox. Can't reproduce in Chrome, Linux Mint

**Comment by gioboa** [comment]
In the first checkbox there is a horizontal line... Maybe it append only under macOS.

**Comment by franckevva** [comment]
Hi, @gioboa 
Thank you for your attention
This graphic problem comes from material icons and we haven't the opportunity to solve it
I found such behavior [here (getmdl.io)](https://getmdl.io/components/index.html#toggles-section/checkbox)
![image](https://user-images.githubusercontent.com/3253797/52621338-16a0ae00-2eb8-11e9-8385-bcc01a2a30d8.png)
